stages:
  - install
  - build
  - deploy

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/
    - docs/.vitepress/dist

install_test:
  stage: install
  only:
    - master
  script:
    - pwd
    - echo '开始安装依赖'
    - npm install
    - echo '结束安装'
    - pwd
  tags:
    - docs_vitepress

build_test:
  stage: build
  only:
    - master
  script:
    - pwd
    - echo '打包开始'
    - npm run build
  tags:
    - docs_vitepress

deploy_test:
  stage: deploy
  only:
    - master
  script:
    - echo '开始发布'
    - rm -rf /usr/local/nginx/html/docs_vitepress/dist
    - cp -rf /home/gitlab-runner/builds/gz3krSst/0/test/docs-vitepress/docs/.vitepress/dist /usr/local/nginx/html/docs_vitepress/dist
  tags:
    - docs_vitepress
